::generated by chat-gpt. and I need to more powerful script in python.
@echo off
setlocal

:: [사용자 지정 변수]
set INPUT=video.mp4
set WIDTH=640
set HEIGHT=360
set BITRATE=300
set FRAMERATE=30

:: 중간 파일명
set YUV_FILE=intermediate.yuv
set AUDIO_FILE=audio.m4a
set STATS_FILE=stats.log
set VIDEO_FILE=encoded.ivf
set OUTPUT_FILE=final_output.mkv

echo -----------------------------------
echo [1] YUV 및 오디오 추출
echo -----------------------------------
ffmpeg -y -i "%INPUT%" -vf scale=%WIDTH%:%HEIGHT% -pix_fmt yuv420p -vsync 0 -r %FRAMERATE% "%YUV_FILE%"
ffmpeg -y -i "%INPUT%" -vn -acodec copy "%AUDIO_FILE%"

echo -----------------------------------
echo [2] 1패스 - 분석 데이터 생성
echo -----------------------------------
SvtAv1EncApp.exe --input "%YUV_FILE%" --input-width %WIDTH% --input-height %HEIGHT% ^
 --fps %FRAMERATE% --input-depth 8 --pass 1 --rc 2 --target-bitrate %BITRATE% --output-stat-file "%STATS_FILE%"

echo -----------------------------------
echo [3] 2패스 - 실제 비디오 인코딩
echo -----------------------------------
SvtAv1EncApp.exe --input "%YUV_FILE%" --input-width %WIDTH% --input-height %HEIGHT% ^
 --fps %FRAMERATE% --input-depth 8 --pass 2 --rc 2 --target-bitrate %BITRATE% ^
 --input-stat-file "%STATS_FILE%" --output "%VIDEO_FILE%"

echo -----------------------------------
echo [4] MKV로 병합
echo -----------------------------------
ffmpeg -y -i "%VIDEO_FILE%" -i "%AUDIO_FILE%" -c:v copy -c:a copy "%OUTPUT_FILE%"

echo -----------------------------------
echo 완료! → %OUTPUT_FILE%
echo -----------------------------------

:: 중간 파일 삭제 (선택사항)
:: del "%YUV_FILE%"
:: del "%AUDIO_FILE%"
:: del "%STATS_FILE%"
:: del "%VIDEO_FILE%"

endlocal
pause